//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS
    {
        public int ID { get; set; }
        public System.Guid CONTENT_UUID { get; set; }
        public string DOC_NAME { get; set; }
        public string UPLOADED_BY { get; set; }
        public System.DateTime DATE_UPLOADED { get; set; }
        public string DOC_EXTERNAL_URI { get; set; }
    }
}
